#!/usr/bin/env ruby

THIS_FILE = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
$:.unshift(File.expand_path(File.join(File.dirname(THIS_FILE),'../lib')))

require 'cli'
Distributor::CLI.start(ARGV)